apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-mirror-data
  namespace: git-mirror
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
